AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Pinata project API

  During the month of March 2023, I'll have a presentation in front of a
  classroom of kids. I want to show them a bit of Mexico, Cloud Computing,
  and AI. More specifically, I want to show them how we can use AI to generate 
  images an how we can use cloud computing to deploy a web application.

Globals:
  Function:
    Timeout: 15
    MemorySize: 128

Parameters:
  TABLE:
    Type: String
    Description: Table name
    Default: Images
  REGION:
    Type: String
    Description: Region name
    Default: eu-central-1
  AWSENV:
    Type: String
    Description: AWS env
    Default: AWS

Resources:
  CreateImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/create_image
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE: !Ref TABLE
          REGION: !Ref REGION
          AWSENV: !Ref AWSENV
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:openai-key-sT7Gwn"
        - DynamoDBCrudPolicy:
            TableName: !Ref ImagesTable
      Events:
        CreateImage:
          Type: Api
          Properties:
            Path: /images
            Method: put
  GetImagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/read_images
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE: !Ref TABLE
          REGION: !Ref REGION
          AWSENV: !Ref AWSENV
          INDEX_NAME: !GetAtt ImagesTable.GlobalSecondaryIndexes[0].IndexName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ImagesTable
      Events:
        GetImages:
          Type: Api
          Properties:
            Path: /images
            Method: get
  ImagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "stage"
          AttributeType: "N"
        - AttributeName: "created_dt"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: !Ref TABLE
      GlobalSecondaryIndexes:
        - IndexName: "stage-created_dt"
          KeySchema:
            - AttributeName: "stage"
              KeyType: "HASH"
            - AttributeName: "created_dt"
              KeyType: "RANGE"
          Projection:
              ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/images/"
